services:

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - ${PORT_API}:8010
    # depends_on:
    #   - db_postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
        CONTAINER_NAME: backend
        DB_DRIVERNAME: ${DB_DRIVERNAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}


    volumes:
        -  ${PATH_LOGS}:/system_logs 
    networks:
      - networks_project

  db_postgres:
    #container_name: db_postgres
    image: postgres:15.2-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
    
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASENAME}

    volumes:
      - ${PATH_VOL_POSTGRES}:/var/lib/postgresql/data
     # - ./config/postgres:/docker-entrypoint-initdb.d
    networks:
      - networks_project

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: America/Sao_Paulo
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./config/pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      - networks_project


networks:
  networks_project:
    driver: bridge