services:

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - ${PORT_API}:8010
    # depends_on:
    #   - db_postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
        CONTAINER_NAME: backend
        DB_DRIVERNAME: ${DB_DRIVERNAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}


    volumes:
        -  ${PATH_LOGS}:/system_logs 
    networks:
      - networks_project





networks:
  networks_project:
    driver: bridge